import React, { useState } from 'react'
import { CAUSE_LABELS, RISK_CONFIG, fmt } from '../constants'
import LeafletMap from '../LeafletMap'

function RiskBadge({level}) {
  const cfg = RISK_CONFIG[level]||RISK_CONFIG.Low
  return (
    <span className="inline-flex items-center gap-1.5 px-3 py-1 rounded-full text-xs font-bold border bg-white shadow-sm" style={{ color: cfg.dot, borderColor: cfg.dot }}>
      <span className="w-2 h-2 rounded-full inline-block" style={{ background: cfg.dot }} />
      {level} Risk
    </span>
  )
}

export default function ResultsPanel({ results }) {
  const [toast, setToast] = useState(false)
  const [copied, setCopied] = useState(false)
  const [advisoryModalOpen, setAdvisoryModalOpen] = useState(false)

  if (!results) {
    return (
      <div className="flex flex-col items-center justify-center h-full gap-4 p-10 bg-gray-50 text-gray-400">
        <div className="text-6xl drop-shadow-sm">🗺️</div>
        <div className="font-bold text-xl text-gray-600">Awaiting Event Data</div>
        <p className="text-sm text-center max-w-sm leading-relaxed text-gray-500">
          Select event parameters in the left panel and click Generate Intelligence to see AI-powered predictions, historical analysis, and resource recommendations.
        </p>
      </div>
    )
  }

  const {data:r, form} = results
  const deploy = async () => {
    try {
      const { API } = await import('../constants')
      const axios = (await import('axios')).default
      const payload = {
  form: {
    event_cause: form.event_cause,
    veh_type: form.veh_type,
    corridor: form.corridor,
    priority: form.priority,
    time: form.time,
    requires_road_closure: form.requires_road_closure,
    event_type: form.event_type,
    latitude: form.latitude,
    longitude: form.longitude,
    police_station: form.police_station,
    description: form.description,
    event_scale: form.event_scale,
    crowd_size: form.crowd_size
  },
  predictions: {
    predicted_duration: r.predicted_duration_minutes,
    personnel: r.personnel_needed,
    barricades: r.barricades_needed,
    congestion_radius_meters: r.congestion_radius_meters,
    commuter_delay_minutes: r.commuter_delay_minutes
  }
}

await axios.post(`${API}/api/deployments`, payload)
      setToast(true)
      setTimeout(()=>setToast(false),3000)
    } catch (err) {
      console.error("Deployment request failed")
      alert("Failed to submit deployment to server.")
    }
  }

  const generateAdvisory = () => {
    const alertMsg = `🚦 TRAFFIC ALERT: ${CAUSE_LABELS[form.event_cause]||form.event_cause} at ${form.corridor}.\nExpect delays of ~${Math.round(r.predicted_duration_minutes)} mins.\nAvoid ${Math.round(r.congestion_radius_meters)}m radius. Suggested diversion route in effect.\n#TraffiSenseAI #BengaluruTraffic`
    navigator.clipboard.writeText(alertMsg)
    setCopied(true)
    setTimeout(() => setCopied(false), 2000)
  }

  return (
    <div className="p-4 sm:p-6 lg:p-8 pb-28 sm:pb-32 flex flex-col gap-6 bg-gray-50 min-h-full overflow-x-hidden">
      {/* Sticky Dashboard Header */}
      <div className="sticky top-0 z-10 bg-gray-50 pb-4 sm:pb-6 border-b border-gray-200/60 shadow-[0_10px_30px_-15px_rgba(0,0,0,0.1)] -mx-4 sm:-mx-6 lg:-mx-8 px-4 sm:px-6 lg:px-8 pt-4 sm:pt-6 lg:pt-8 mb-6">
        {/* Header */}
        <div className="flex justify-between items-start flex-wrap gap-4 mb-6">
          <div>
            <h2 className="text-2xl sm:text-2xl sm:text-3xl font-black text-gray-900 tracking-tight flex items-center gap-2">
              Intelligence Report
            </h2>
            <p className="text-sm text-gray-500 font-bold mt-1">Generated by TraffiSense AI Engine</p>
          </div>
          <RiskBadge level={r.risk_level}/>
        </div>

        <div className="flex flex-col xl:flex-row gap-6">
          {/* Left: 4 KPI Cards */}
          <div className="flex-1 grid grid-cols-1 sm:grid-cols-2 gap-4">
            <div className="bg-white rounded-2xl shadow-sm p-4 sm:p-5 border border-gray-100 flex flex-col justify-between">
              <div className="flex items-center gap-2 mb-3">
                <div className="w-8 h-8 rounded-lg bg-blue-50 text-blue-600 flex items-center justify-center text-lg">⏱️</div>
                <div className="text-[0.65rem] font-extrabold text-gray-400 uppercase tracking-widest">Est. Clearance</div>
              </div>
              <div className="flex items-end gap-1 mb-2">
                <span className="text-2xl sm:text-3xl font-black text-gray-900 leading-none">{r.predicted_duration_minutes.toFixed(0)}</span>
                <span className="text-sm font-bold text-gray-400 mb-0.5">mins</span>
              </div>
              <div className="text-[0.65rem] font-bold text-blue-600 bg-blue-50 py-1 px-2 rounded-md inline-block border border-blue-100 mt-auto">
                Model Confidence: High
              </div>
            </div>

            <div className="bg-white rounded-2xl shadow-sm p-4 sm:p-5 border border-gray-100 flex flex-col justify-between">
              <div className="flex items-center gap-2 mb-3">
                <div className="w-8 h-8 rounded-lg bg-green-50 text-green-600 flex items-center justify-center text-lg">👮</div>
                <div className="text-[0.65rem] font-extrabold text-gray-400 uppercase tracking-widest">Personnel</div>
              </div>
              <div className="text-2xl sm:text-3xl font-black text-gray-900 mb-1">{r.personnel_needed}</div>
              <div className="text-[0.65rem] font-bold text-gray-400 mt-auto">Officers needed</div>
            </div>

            <div className="bg-white rounded-2xl shadow-sm p-4 sm:p-5 border border-gray-100 flex flex-col justify-between">
              <div className="flex items-center gap-2 mb-3">
                <div className="w-8 h-8 rounded-lg bg-yellow-50 text-yellow-500 flex items-center justify-center text-lg">🚧</div>
                <div className="text-[0.65rem] font-extrabold text-gray-400 uppercase tracking-widest">Barricades</div>
              </div>
              <div className="text-2xl sm:text-3xl font-black text-gray-900 mb-1">{r.barricades_needed}</div>
              <div className="text-[0.65rem] font-bold text-gray-400 mt-auto">Units required</div>
            </div>

            <div className="bg-white rounded-2xl shadow-sm p-4 sm:p-5 border border-gray-100 flex flex-col justify-between">
              <div className="flex items-center gap-2 mb-3">
                <div className="w-8 h-8 rounded-lg bg-purple-50 text-purple-600 flex items-center justify-center text-lg">🛑</div>
                <div className="text-[0.65rem] font-extrabold text-gray-400 uppercase tracking-widest">Road Closure</div>
              </div>
              <div className="text-2xl sm:text-3xl font-black text-gray-900 mb-1">{r.road_closure_probability}%</div>
              <div className="text-[0.65rem] font-bold text-gray-400 mt-auto">Historical probability</div>
            </div>
          </div>

          {/* Right: ROI & Impact Analysis */}
          <div className="w-full xl:w-[350px] p-4 sm:p-6 shrink-0 bg-white rounded-2xl shadow-sm p-6 border border-gray-100 flex flex-col justify-center">
            <div className="flex justify-between items-center mb-5">
              <div className="text-[0.65rem] font-extrabold text-gray-400 uppercase tracking-widest">ROI & Impact Analysis</div>
              <span className="bg-purple-50 text-purple-600 border border-purple-200 px-2 py-0.5 rounded text-[0.65rem] font-bold">Predictive AI</span>
            </div>

            <div className="mb-5">
              <div className="flex justify-between text-xs font-bold text-gray-500 mb-2">
                <span className="flex items-center gap-1">🛑 Without TraffiSense AI</span>
                <span className="text-red-500 font-black">{Math.round(r.commuter_delay_minutes * 3.2)} mins</span>
              </div>
              <div className="w-full bg-red-50 rounded-full h-3 overflow-hidden border border-red-100">
                <div className="bg-gradient-to-r from-red-400 to-red-500 h-full rounded-full" style={{ width: '95%' }}></div>
              </div>
            </div>
            
            <div>
              <div className="flex justify-between text-xs font-bold text-gray-500 mb-2">
                <span className="flex items-center gap-1">✅ With AI Diversion</span>
                <span className="text-green-600 font-black">{Math.round(r.commuter_delay_minutes)} mins</span>
              </div>
              <div className="w-full bg-green-50 rounded-full h-3 overflow-hidden border border-green-100 relative">
                <div className="bg-gradient-to-r from-green-400 to-green-500 h-full rounded-full absolute left-0 top-0 transition-all duration-1000" style={{ width: '31%' }}></div>
              </div>
            </div>

            <div className="mt-5 p-2 bg-fk-blue/5 border border-fk-blue/10 rounded-lg flex items-center justify-between">
              <span className="text-[0.65rem] font-bold text-fk-blue uppercase tracking-widest">Time Saved per Commuter</span>
              <span className="text-sm font-black text-fk-blue">~{Math.round(r.commuter_delay_minutes * 2.2)} mins</span>
            </div>
          </div>
        </div>
      </div>

      {/* Historical Context Panel */}
      <div className="bg-white rounded-xl shadow-sm p-4 sm:p-6 border border-gray-100">
        <div className="text-sm font-bold text-gray-500 uppercase tracking-wider mb-4">Historical Context</div>
        <div className="flex flex-col divide-y divide-gray-100">
          <div className="flex justify-between py-3">
            <span className="text-sm text-gray-600 font-medium">Similar events (cause + corridor)</span>
            <span className="text-sm font-bold text-gray-900">{r.similar_past_events}</span>
          </div>
          <div className="flex justify-between py-3">
            <span className="text-sm text-gray-600 font-medium">Historical avg clearance</span>
            <span className="text-sm font-bold text-gray-500">{fmt(r.historical_avg_duration)} min</span>
          </div>
          <div className="flex justify-between py-3">
            <span className="text-sm text-gray-600 font-medium">Road closure probability</span>
            <span className={`text-sm font-bold ${r.road_closure_probability > 40 ? 'text-red-500' : 'text-green-500'}`}>{r.road_closure_probability}%</span>
          </div>
          <div className="flex justify-between py-3">
            <span className="text-sm text-gray-600 font-medium">AI predicted clearance</span>
            <span className="text-sm font-bold text-blue-600">{fmt(r.predicted_duration_minutes)} min</span>
          </div>
        </div>
      </div>

      {/* Alert Box */}
      {r.ripple_effect_warning && (
        <div className="bg-yellow-50 border-l-4 border-yellow-400 p-4 rounded-r-lg shadow-sm flex items-start gap-3">
          <span className="text-xl">⚠️</span>
          <div>
            <div className="font-bold text-yellow-900 text-sm mb-1">Ripple Effect Alert</div>
            <div className="text-sm text-yellow-800">{r.ripple_effect_warning}</div>
          </div>
        </div>
      )}



      {/* Map Section */}
      <div className="bg-white rounded-xl shadow-sm p-6 border border-gray-100">
        <div className="flex justify-between items-center mb-4">
          <div className="text-sm font-bold text-gray-500 uppercase tracking-wider">Diversion Route Mapping</div>
          <div className="flex gap-2">
            <span className="bg-blue-50 text-blue-600 border border-blue-200 px-2 py-1 rounded text-xs font-bold flex items-center gap-1">
              <span className="w-2 h-2 rounded-full bg-blue-500 animate-pulse"></span>
              Live Traffic Overlay
            </span>
          </div>
        </div>
        <div className="bg-blue-100 rounded-lg min-h-[260px] sm:min-h-[350px] lg:min-h-[400px] overflow-hidden border border-gray-200 relative">
          <LeafletMap
            center={{lat:form.latitude, lng:form.longitude}}
            diversionRoute={r.diversion_route}
            radius={r.congestion_radius_meters}
          />
        </div>
        <button 
        onClick={deploy}
        className="w-full py-3 sm:py-4 text-base sm:text-lg mt-2 bg-fk-blue hover:bg-blue-700 text-white font-extrabold rounded-xl shadow-lg hover:shadow-xl hover:-translate-y-0.5 transition-all flex items-center justify-center gap-2 text-lg active:scale-95"
      >
        <span className="animate-pulse">🚀</span> Deploy TraffiSense AI Field Units
      </button>
      </div>

      {toast && (
        <div className="fixed bottom-20 right-4 sm:right-8 z-50 flex items-center gap-3 p-4 bg-white border border-green-200 rounded-xl shadow-lg animate-bounce">
          <span className="text-2xl">✅</span>
          <div>
            <div className="font-bold text-gray-900 text-sm">Units Deployed!</div>
            <div className="text-xs text-gray-500 font-medium">Personnel & barricades dispatched.</div>
          </div>
        </div>
      )}

      {/* Floating Action Button */}
      <button 
        onClick={() => setAdvisoryModalOpen(true)}
        className="fixed bottom-4 sm:bottom-8 right-4 sm:right-8 z-40 bg-fk-blue hover:bg-blue-700 text-white p-4 rounded-full shadow-2xl hover:scale-105 hover:-translate-y-1 transition-all flex items-center gap-3 pr-6 group"
      >
        <span className="text-2xl bg-white/20 p-2 rounded-full">📢</span>
        <span className="font-extrabold tracking-wide hidden md:block">Post Public Advisory</span>
      </button>

      {/* Advisory Modal */}
      {advisoryModalOpen && (
        <div className="fixed inset-0 z-[100] flex items-center justify-center p-4 bg-gray-900/60 backdrop-blur-sm">
          <div className="bg-white rounded-2xl shadow-2xl max-w-lg w-full p-5 sm:p-8 relative overflow-hidden">
            <button 
              onClick={() => setAdvisoryModalOpen(false)}
              className="absolute top-4 right-4 w-8 h-8 flex items-center justify-center rounded-full bg-gray-100 hover:bg-gray-200 text-gray-600 transition-colors"
            >
              ✕
            </button>
            <h2 className="text-2xl font-black text-gray-900 mb-2 flex items-center gap-3">
              <span className="text-3xl">📢</span> Automated Advisory
            </h2>
            <p className="text-gray-500 text-sm font-medium mb-6">Review and broadcast the AI-generated traffic alert.</p>
            
            <div className="bg-gray-50 p-4 rounded-xl border border-gray-200 text-gray-800 text-sm font-medium leading-relaxed font-mono whitespace-pre-wrap shadow-inner mb-6 relative">
              <span className="absolute top-2 right-2 bg-green-100 text-green-700 border border-green-200 px-2 py-0.5 rounded text-[0.65rem] font-bold">Auto-generated</span>
              <br/>
              🚦 TRAFFIC ALERT: {CAUSE_LABELS[form.event_cause]||form.event_cause} at {form.corridor}.
              {'\n'}Expect delays of ~{Math.round(r.predicted_duration_minutes)} mins.
              {'\n'}Avoid {Math.round(r.congestion_radius_meters)}m radius. Suggested diversion route in effect.
              {'\n'}#TraffiSenseAI #BengaluruTraffic
            </div>

            <div className="flex flex-col gap-3">
              <button onClick={generateAdvisory} className={`w-full py-3 rounded-xl font-bold transition-colors flex items-center justify-center gap-2 ${copied ? 'bg-green-50 text-green-600 border border-green-200' : 'bg-gray-100 hover:bg-gray-200 text-gray-800'}`}>
                {copied ? '✅ Copied to Clipboard!' : '📋 Copy for WhatsApp'}
              </button>
              <a href={`https://twitter.com/intent/tweet?text=${encodeURIComponent(`🚦 TRAFFIC ALERT: ${CAUSE_LABELS[form.event_cause]||form.event_cause} at ${form.corridor}.\nExpect delays of ~${Math.round(r.predicted_duration_minutes)} mins.\nAvoid ${Math.round(r.congestion_radius_meters)}m radius. Suggested diversion route in effect.\n#TraffiSenseAI #BengaluruTraffic`)}`} target="_blank" rel="noreferrer" className="w-full bg-[#1DA1F2] hover:bg-[#1a91da] text-white font-bold py-3 rounded-xl transition-colors flex items-center justify-center gap-2">
                🐦 Post to X (Twitter)
              </a>
            </div>
          </div>
        </div>
      )}
    </div>
  )
}

